name: CI
on:
  - push
  - pull_request

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') && github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: pnpm/action-setup@v2
        with:
          version: ^7.1.5
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpx nx affected --target=lint
      - run: pnpx nx affected --target=build
      - run: pnpx nx affected --target=test --codeCoverage --coverageReporters=json,text,text-summary
      - name: Publish code coverage report
        if: contains(github.ref, 'main')
        uses: codecov/codecov-action@v3
        with:
          directory: coverage/packages

  pr:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') && github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: pnpm/action-setup@v2
        with:
          version: ^7.1.5
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpx nx affected --target=lint
      - run: pnpx nx affected --target=build
      - run: pnpx nx affected --target=test --codeCoverage --coverageReporters=json,text,text-summary
      - name: Publish code coverage report
        uses: codecov/codecov-action@v3
        with:
          directory: coverage/packages
